config/routes.rb
Rails.application.routes.draw do
  resources :arts
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/art.rb
class Art < ApplicationRecord
  validates :title, presence: true, length: { maximum: 50 }
  validates :content, presence: true, length: { maximum: 1000 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/arts_controller.rb
class ArtsController < ApplicationController
  PER_PAGE = 20
  before_action :set_art, only: %i[show edit update destroy]

  def index
    @q = Art.ransack(params[:q])
    @arts = Art.order(id: :asc)
    @arts = @q.result.page(params[:page]).per(PER_PAGE)
  end

  def show
  end

  def new
    @art = Art.new
  end

  def create
    @art = Art.new(art_params)
    if @art.save
      redirect_to arts_path, notice: "投稿しました"
    else
      flash.now[:alert] = "投稿に失敗しました"
      render :new
    end
  end

  def edit
  end

  def update
    if @art.update(art_params)
      redirect_to @art, notice: "変更しました"
    else
      flash.now[:alert] = "変更に失敗しました"
      render :edit
    end 
  end

  def destroy
    @art.destroy
    redirect_to arts_path, alert: "削除しました"
  end

  private

  def set_art
    @art = Art.find(params[:id])
  end

  def art_params
    params.require(:art).permit(:title, :content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/arts/_form.html.erb
<%= render "layouts/error_messages" %>
<%= form_with model: @art, local: true do |form| %>
  <div class="form-group">
    <%= form.label :title %>
    <%= form.text_field :title, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= form.label :content %>
    <%= form.text_area :content, class: "form-control", rows: 10 %>
  </div>
  <div>
    <%= form.submit button_value, class: "btn btn-primary btn-block" %>
  </div>
<% end %>

app/views/arts/edit.html.erb
<h1>編集</h1>
<%= render "form", button_value: "変更"%>

app/views/arts/index.html.erb
<%= search_form_for @q do |f| %>
  <%= f.label :title_cont, "タイトル" %>
  <%= f.search_field :title_cont %>
  <%= f.submit "検索" %>
<% end %>

<h1 class="text-center">楽曲一覧</h1>
<table class="table table-bordered table-striped mt-4">
  <thead class="table-primary">
    <tr>
      <th scope="col" class="w-100">タイトル</th>
      <th scope="col"></th>
    </tr>
  </thead>
  <tbody>
    <% @arts.each do |art| %>
      <tr>
        <td class="break-word"><%= art.title %></td>
        <td class="text-nowrap">
          <%= link_to art, class: "btn btn-primary" do %>
            <i class="fas fa-envelope-open-text"></i> <span class="d-none d-md-inline"> 詳細</span>
          <% end %>
          <%= link_to edit_art_path(art), class: "btn btn-success" do %>
            <i class="far fa-edit"></i> <span class="d-none d-md-inline"> 編集</span>
          <% end %>
          <%= link_to art, method: :delete, data: { confirm: "削除しますか?" }, class: "btn btn-danger" do %>
            <i class="far fa-trash-alt"></i> <span class="d-none d-md-inline"> 削除</span>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= paginate @arts %>

app/views/arts/new.html.erb
<h1>新規登録</h1>
<%= render "form", button_value: "登録"%>

app/views/arts/show.html.erb
<h1 class="text-center">楽曲詳細</h1>
<section class="card border-dark mt-5">
  <div class="card-header">
    <h4><%= @art.title %></h4>
  </div>
  <div class="card-body">
    <p class="card-text"><%= simple_format(h @art.content) %></p>
  </div>
</section>

app/views/layouts/_error_messages.html.erb
<% if @art.errors.any? %>
  <% @art.errors.full_messages.each do |msg| %>
    <div class="alert alert-danger" role="alert">
      <a href="#" class="close" data-dismiss="alert">×</a>
      <%= msg %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_flash.html.erb
<% flash.each do |flash_type, msg| %>
  <div class="alert alert-<%= flash_type %>" role="alert">
    <a href="#" class="close" data-dismiss="alert">×</a>
    <%= msg %>
  </div>
<% end %>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-sm navbar-dark bg-primary fixed-top">
  <span class="navbar-brand">n-buna 音楽作品一覧</span>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
    <div class="navbar-nav">
      <%= link_to "楽曲一覧", arts_path, class: "nav-item nav-link active" %>
      <%= link_to "新規登録", new_art_path, class: "nav-item nav-link active" %>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Yorushika</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <header>
      <%= render "layouts/header" %>
    </header>
    <main>
      <%= render "layouts/flash" %>
      <div class="base-container">
        <%= yield %>
      </div>
    </main>
  </body>
</html>